// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int64              `json:"id"`
	UserID    string             `json:"user_id"`
	EventType string             `json:"event_type"`
	Value     int64              `json:"value"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}
