// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (user_id, event_type, value, timestamp)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, event_type, value, timestamp
`

type CreateEventParams struct {
	UserID    string             `json:"user_id"`
	EventType string             `json:"event_type"`
	Value     int64              `json:"value"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.UserID,
		arg.EventType,
		arg.Value,
		arg.Timestamp,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Value,
		&i.Timestamp,
	)
	return i, err
}

const listAgrregatedEvents = `-- name: ListAgrregatedEvents :many
SELECT
  SUM(value)::BIGINT as event_count,
  event_type
FROM
  events
WHERE user_id = $1
GROUP BY event_type
`

type ListAgrregatedEventsRow struct {
	EventCount int64  `json:"event_count"`
	EventType  string `json:"event_type"`
}

func (q *Queries) ListAgrregatedEvents(ctx context.Context, userID string) ([]ListAgrregatedEventsRow, error) {
	rows, err := q.db.Query(ctx, listAgrregatedEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgrregatedEventsRow
	for rows.Next() {
		var i ListAgrregatedEventsRow
		if err := rows.Scan(&i.EventCount, &i.EventType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
