// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	ListAgrregatedEvents(ctx context.Context, userID string) ([]ListAgrregatedEventsRow, error)
}

var _ Querier = (*Queries)(nil)
