services:
  events-processing-postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d events-processing"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
      build: .
      volumes:
      - .:/app
      env_file:
        - .env
      ports:
        - "${PORT}:${PORT}"
      environment:
        - DB_DSN=${DB_DSN}
        - PORT=${PORT}
      depends_on:
        events-processing-postgres:
          condition: service_healthy
  test:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - DB_DSN=${DB_DSN}
      - CGO_ENABLED=1
    depends_on:
      events-processing-postgres:
        condition: service_healthy
    entrypoint: ""
    command: go test -race -cover -coverpkg=my-app/internal/events ./internal/tests/events
volumes:
  postgres-data:
